<?php

/**
 * @file
 * Contains paragraphs_sets_plugins.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function paragraphs_sets_plugins_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the paragraphs_sets_plugins module.
    case 'help.page.paragraphs_sets_plugins':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Data transform plugin system for Paragraphs Sets') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_paragraphs_set_data_alter().
 */
function paragraphs_sets_plugins_paragraphs_set_data_alter(&$data, $context) {
  // Run source data through plugin system.
  $plugin_processor = \Drupal::service('paragraphs_sets_plugins.plugin_transform_processor');
  $plugin_processor->transformRecursively($data, $context);
}
